### ISSUE TITLE
H5 file not closed properly upon ValueError in Pre-alignment

### ISSUE THREAD

**Issue by coquelin77** [SiLab-Bonn/testbeam_analysis#106]
1st error:
Traceback (most recent call last):
  File "/home/daniel/MasterThesis/testbeam_analysis/testbeam_analysis/gui/gui_widgets/worker.py", line 47, in work
    self.main_func(func, kwargs)
  File "/home/daniel/MasterThesis/testbeam_analysis/testbeam_analysis/gui/gui_widgets/analysis_widgets.py", line 445, in _call_func
    val = func(**kwargs)
  File "/home/daniel/MasterThesis/testbeam_analysis/testbeam_analysis/dut_alignment.py", line 96, in correlate_cluster
    (start_indices[dut_index], column_correlations[dut_index - 1], row_correlations[dut_index - 1]) = dut_result.get()
  File "/home/daniel/anaconda2/lib/python2.7/multiprocessing/pool.py", line 572, in get
    raise self._value
ValueError: Column and/or row index is smaller than 0.5

2nd error:
HDF5 error back trace

  File "H5F.c", line 491, in H5Fcreate
    unable to create file
  File "H5Fint.c", line 1305, in H5F_open
    unable to lock the file
  File "H5FD.c", line 1839, in H5FD_lock
    driver lock request failed
  File "H5FDsec2.c", line 940, in H5FD_sec2_lock
    unable to lock file, errno = 11, error message = 'Resource temporarily unavailable'

End of HDF5 error back trace

Unable to open/create file '/home/daniel/MasterThesis/testbeam_analysis/testbeam_analysis/gui/Correlation.h5'

**Comment by DavidLP** [comment]
One cannot access a file when you use it in another process. Likely after the exception a process was still accessing it. Nothing one can do about that.
