### ISSUE TITLE
Crash in track fitting because of plotting

### ISSUE THREAD

**Issue by coquelin77** [SiLab-Bonn/testbeam_analysis#114]
Plotting should never cause a crash. Traceback:
```python
Traceback (most recent call last):
  File "/home/daniel/MasterThesis/testbeam_analysis/testbeam_analysis/gui/gui_widgets/worker.py", line 54, in work
    self.main_func(self.args)
  File "/home/daniel/MasterThesis/testbeam_analysis/testbeam_analysis/gui/gui_widgets/plotter.py", line 226, in _get_figs
    **self.kwargs[multi_plot_key])
  File "/home/daniel/MasterThesis/testbeam_analysis/testbeam_analysis/tools/plot_utils.py", line 930, in plot_events
    ax.set_zlim(np.amin(np.array(z)), np.amax(np.array(z)))
  File "/home/daniel/anaconda2/lib/python2.7/site-packages/mpl_toolkits/mplot3d/axes3d.py", line 732, in set_zlim3d
    bottom = self._validate_converted_limits(bottom, self.convert_zunits)
  File "/home/daniel/anaconda2/lib/python2.7/site-packages/matplotlib/axes/_base.py", line 3040, in _validate_converted_limits
    raise ValueError("Axis limits cannot be NaN or Inf")
ValueError: Axis limits cannot be NaN or Inf
```

**Comment by leloup314** [comment]
@coquelin77 Does the GUI actually crash or is the exception caught in the exceptions window? Usually any exception raised during plotting should be caught and handed through to the exception window.

**Comment by leloup314** [comment]
I'm closing this since the GUI **doesn't crash** but behaves as expected and opens an exception window.

**Comment by DavidLP** [comment]
It was not a GUI related bug, since the GUI behaved as expected, I agree. But it is a plotting bug that I implemented 2 years ago ;-).

**Comment by leloup314** [comment]
Ah, okay, so I'm reopening this then but removing the `gui` label.
