### ISSUE TITLE
[tools.plot_utils] Crash during interactive prealignment cutting

### ISSUE THREAD

**Issue by DavidLP** [SiLab-Bonn/testbeam_analysis#53]
Crash when using auto cut.

``` bash
Traceback (most recent call last):
  File "C:\Users\DavidLP\Miniconda2\lib\site-packages\matplotlib\backends\backend_qt5.py", line 300, in mouseReleaseEvent
    guiEvent=event)
  File "C:\Users\DavidLP\Miniconda2\lib\site-packages\matplotlib\backend_bases.py", line 1932, in button_release_event
    self.callbacks.process(s, event)
  File "C:\Users\DavidLP\Miniconda2\lib\site-packages\matplotlib\cbook.py", line 549, in process
    proxy(*args, **kwargs)
  File "C:\Users\DavidLP\Miniconda2\lib\site-packages\matplotlib\cbook.py", line 416, in __call__
    return mtd(*args, **kwargs)
  File "C:\Users\DavidLP\Miniconda2\lib\site-packages\matplotlib\widgets.py", line 229, in _release
    func(event)
  File "c:\users\davidlp\git\testbeam_analysis\testbeam_analysis\tools\plot_utils.py", line 289, in update_auto
    error_limit = max(error_median + error_std * 2, np.percentile(np.abs(mean_error_fitted[selected_data]), mean_error_percentile))
  File "C:\Users\DavidLP\Miniconda2\lib\site-packages\numpy\lib\function_base.py", line 3699, in percentile
    interpolation=interpolation)
  File "C:\Users\DavidLP\Miniconda2\lib\site-packages\numpy\lib\function_base.py", line 3425, in _ureduce
    r = func(a, **kwargs)
  File "C:\Users\DavidLP\Miniconda2\lib\site-packages\numpy\lib\function_base.py", line 3816, in _percentile
    x1 = take(ap, indices_below, axis=axis) * weights_below
  File "C:\Users\DavidLP\Miniconda2\lib\site-packages\numpy\core\fromnumeric.py", line 123, in take
    return take(indices, axis, out, mode)
IndexError: cannot do a non-empty take from an empty axes.
```

**Comment by laborleben** [comment]
See #54.
