### ISSUE TITLE
[development] test_track_finding.py fails when when not jitted

### ISSUE THREAD

**Issue by laborleben** [SiLab-Bonn/testbeam_analysis#66]
Removing the `@njit` decorator from `_find_tracks_loop` (https://github.com/SiLab-Bonn/testbeam_analysis/blob/79a4857728a0259369d0ae8c4c6bdfe757f05523/testbeam_analysis/track_analysis.py#L590) will lead to a failing unit test:
```
Traceback (most recent call last):
  File "/home/jens/dev/testbeam_analysis/testbeam_analysis/testing/test_track_analysis.py", line 56, in test_track_finding
    chunk_size=293)
  File "/home/jens/dev/testbeam_analysis/testbeam_analysis/track_analysis.py", line 113, in find_tracks
    _find_tracks_loop(tracklets_data_chunk, tr_x, tr_y, tr_z, tr_xerr, tr_yerr, tr_zerr, tr_charge, column_sigma, row_sigma, min_cluster_distance)
  File "/home/jens/dev/testbeam_analysis/testbeam_analysis/track_analysis.py", line 662, in _find_tracks_loop
    _set_dut_track_quality(tr_x, tr_y, track_index, dut_index, actual_track, actual_track_column, actual_track_row, actual_column_sigma, actual_row_sigma)
UnboundLocalError: local variable 'actual_track_column' referenced before assignment
```

**Comment by DavidLP** [comment]
Weird.

**Comment by DavidLP** [comment]
Will look into it when I find time

**Comment by DavidLP** [comment]
Fixed.
